### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException while building from /

### ISSUE THREAD

**Issue by nettoyeur** [maven-nar/nar-maven-plugin#154]
If I build from the root dir ( ``mvn -f ...`` ) build failed with 
> Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile (default-nar-compile) on project nar-maven-plugin-issue: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile failed: String index out of range: 2 -> [Help 1]

pom.xml: https://gist.github.com/nettoyeur/786efff0c50d71f6f931

```sh
$ cd /tmp/builder/nar-issue
$ mvn clean compile -f /tmp/builder/nar-issue/pom.xml
...
[INFO] BUILD SUCCESS
...
$ cd /
$ mvn clean compile -f /tmp/builder/nar-issue/pom.xml
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.876 s
[INFO] Finished at: 2015-03-09T16:47:36+01:00
[INFO] Final Memory: 11M/31M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile (default-nar-compile) on project nar-maven-plugin-issue: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile failed: String index out of range: 2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile (default-nar-compile) on project nar-maven-plugin-issue: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile failed: String index out of range: 2
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-nar-compile of goal com.github.maven-nar:nar-maven-plugin:3.2.0:nar-compile failed: String index out of range: 2
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 2
        at java.lang.String.substring(String.java:1950)
        at com.github.maven_nar.cpptasks.CUtil.getRelativePath(CUtil.java:214)
        at com.github.maven_nar.cpptasks.compiler.CommandLineCompiler.addIncludes(CommandLineCompiler.java:97)
        at com.github.maven_nar.cpptasks.compiler.CommandLineCompiler.createConfiguration(CommandLineCompiler.java:362)
        at com.github.maven_nar.cpptasks.compiler.AbstractCompiler.createConfiguration(AbstractCompiler.java:82)
        at com.github.maven_nar.cpptasks.ProcessorDef.createConfiguration(ProcessorDef.java:203)
        at com.github.maven_nar.cpptasks.CCTask.getTargets(CCTask.java:1128)
        at com.github.maven_nar.cpptasks.CCTask.execute(CCTask.java:593)
        at com.github.maven_nar.NarCompileMojo.createLibrary(NarCompileMojo.java:431)
        at com.github.maven_nar.NarCompileMojo.narExecute(NarCompileMojo.java:105)
        at com.github.maven_nar.AbstractNarMojo.execute(AbstractNarMojo.java:302)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

**Comment by ctrueden** [comment]
Your example POM has `BUILD SUCCESS` on my OS X 10.10 system with Maven 3.2.5. What is your AO(L)? Which version of Maven are you using? (`mvn --version`). The NAR plugin requires Maven 3.

Have you compared your POM vs. the [working examples linked in the FAQ](https://github.com/maven-nar/nar-maven-plugin/wiki/Frequently_Asked_Questions#q-where-can-i-find-a-working-example-of-how-to-configure-the-nar-plugin)? Do those examples build on your system?

**Comment by nettoyeur** [comment]
I have  Ubuntu 14.04.2 LTS
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/apache-maven-3.2.5
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "2.6.32-34-pve", arch: "amd64", family: "unix"
...
Setting project property: nar.aol -> amd64-Linux-gpp
Setting project property: nar.arch -> amd64
Setting project property: nar.aol.key -> amd64.Linux.gpp
Setting project property: nar.linker -> g++
Setting project property: nar.os -> Linux
```

**Comment by nettoyeur** [comment]
I'll check with examples later

**Comment by nettoyeur** [comment]
My understanding of this issue:

```
$ cd /
$ mvn -f /tmp/test/imagej-launcher/pom.xml clean package -X
...
[DEBUG] Project base dir set to: /
...
```
File [CUtils.java, line 214](https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/java/com/github/maven_nar/cpptasks/CUtil.java#L214) contains
```java
if (canonicalBase.substring(0, 2).equals("\\\\")) {
```

that leads to exception because ``canonicalBase.length == 1`` as (canonicalBase == "/")

**Comment by ctrueden** [comment]
@nettoyeur Thanks for the diagnosis. I filed PR #155 which might address the issue. Closing this issue in favor of that one.
